### ISSUE TITLE
Error while trying to train

### ISSUE THREAD

**Issue by alaxinbaby** [open-mmlab/mmsr#19]
After running 'python train.py -opt options/train/train_SRResNet.yml' with DIV2K dataset,I get this error:
`export CUDA_VISIBLE_DEVICES=0,1
Traceback (most recent call last):
  File "/data/thrc_shx/PycharmProjects/mmsr-master/codes/train.py", line 312, in <module>
    main()
  File "/data/thrc_shx/PycharmProjects/mmsr-master/codes/train.py", line 46, in main
    init_dist()
  File "/data/thrc_shx/PycharmProjects/mmsr-master/codes/train.py", line 26, in init_dist
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/thrc_shx/anaconda3/envs/py36pytorch/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/thrc_shx/anaconda3/envs/py36pytorch/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 119, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

Process finished with exit code 1`

Any help is very much appreciated.

**Comment by alaxinbaby** [comment]
RESOLVED!!

**Comment by sxpro** [comment]
> RESOLVED!!

Could tell me how to  RESOLVED? ths
