### ISSUE TITLE
create lmdb error

### ISSUE THREAD

**Issue by piajun** [open-mmlab/mmsr#31]
I use my own dataset which has three big images in different size. Then I crop these images in 182 smaller images but they have 3 types of size. Then I use extract_subimages.py and achieve 14392 images with size of 480*480. When I try to use create_lmdb.py , I found an error said:

runfile('C:/Users/ThinkPad/Desktop/SR/mmsr-master/codes/data_scripts/create_lmdb.py', wdir='C:/Users/ThinkPad/Desktop/SR/mmsr-master/codes/data_scripts')
Reloaded modules: data, data.util, utils, utils.util
Reading image path list ...
data size per image is:  691200
Traceback (most recent call last):

  File "<ipython-input-7-a46b46a05e5e>", line 1, in <module>
    runfile('C:/Users/ThinkPad/Desktop/SR/mmsr-master/codes/data_scripts/create_lmdb.py', wdir='C:/Users/ThinkPad/Desktop/SR/mmsr-master/codes/data_scripts')

  File "D:\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "D:\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ThinkPad/Desktop/SR/mmsr-master/codes/data_scripts/create_lmdb.py", line 412, in <module>
    main()

  File "C:/Users/ThinkPad/Desktop/SR/mmsr-master/codes/data_scripts/create_lmdb.py", line 40, in main
    general_image_folder(opt)

  File "C:/Users/ThinkPad/Desktop/SR/mmsr-master/codes/data_scripts/create_lmdb.py", line 106, in general_image_folder
    env = lmdb.open(lmdb_save_path, map_size=data_size * 10)

Error: C:/Users/ThinkPad/Desktop/SR/changping-GF2/train_sub_HR.lmdb: ���̿ռ䲻�㡣

I donnot know how to debug this error, can anybody help me?

**Comment by peteryuX** [comment]
Check you have enough disk space?

**Comment by piajun** [comment]
> Check you have enough disk space?

Yeah, this may be the point, I change my computer to a sever and it runs well.
Thank u!
