### ISSUE TITLE
ESRGAN Training fail with val_data['LQs'].unsqueeze_(0)

### ISSUE THREAD

**Issue by Dejan1969** [open-mmlab/mmsr#60]
Hello 
I'm trying to train ESRGAN on 2 GPU (RTX 2080 TI). Training crash after this error:

20-03-14 20:58:49.211 - INFO: [epoch:  0, iter:   4,900, lr:(1.000e-04,)] l_g_pix: 5.1419e-04 l_g_fea: 1.7966e+00 l_g_gan: 6.4983e-02 l_d_real: 1.4380e-06 l_d_fake: 1.5758e-06 D_real: 5.7167e+01 D_fake: 4.4170e+01 
20-03-14 20:59:32.886 - INFO: [epoch:  0, iter:   5,000, lr:(1.000e-04,)] l_g_pix: 6.5671e-04 l_g_fea: 1.5129e+00 l_g_gan: 2.0994e-02 l_d_real: 1.3033e-02 l_d_fake: 1.0278e-02 D_real: 3.3355e+01 D_fake: 2.9180e+01 
[                              ] 0/100, elapsed: 0s, ETA:
Start...
Traceback (most recent call last):
  File "train.py", line 310, in <module>
    main()
  File "train.py", line 220, in main
    val_data['LQs'].unsqueeze_(0)
KeyError: 'LQs'
[2F[J[------------------------------] 1/100, 0.3 task/s, elapsed: 3s, ETA:   305s
Test 0801
[2F[J[------------------------------] 2/100, 0.5 task/s, elapsed: 4s, ETA:   194s
Test 0802
[2F[J[------------------------------] 3/100, 0.4 task/s, elapsed: 7s, ETA:   219s

Any idea on what's causing this ?

**Comment by Dejan1969** [comment]
BTW it's not quite clear, should I process validation data set the same way as train set? I mean with script data_scripts/extract_subimages.py ? I'm using DIV2K custom downscaled LR sets (downscaled 4x to 50% compressed jpgs and coverted to png with imagemagick). Idea is to fix jpeg compression artifacts. Is ESRGAN right tool for this? I've had some success with SRGAN 2x on tensorflow.

**Comment by Dejan1969** [comment]
Has something to do with with training on multiple GPU-s, however I'm unable to debug this on my machine.
Anyway manu thanks for great work

**Comment by Dejan1969** [comment]
Never mind
