### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 1, 128, 128] to have 3 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by Darrenxc** [open-mmlab/mmsr#66]
I followed the instructions which are described in the DATASETS.md  and training. the code can be run before the first epoch, the 5000 iterations. After 5000 iterations, I got the error, showing below:
RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 1, 128, 128] to have 3 channels, but got 1 channels instead. 

20-04-02 08:55:26.448 - INFO: [epoch:  0, iter:   5,000, lr:(1.000e-04,)] l_g_pix: 1.4000e-04 l_g_fea: 3.8132e-01 l_g_gan: 2.2431e-02 l_d_real: 5.8011e-03 l_d_fake: 5.8231e-03 D_real: 1.1074e+02 D_fake: 1.0627e+02
[>>>>--------------------------] 2/14, 0.6 task/s, elapsed: 3s, ETA:    19s
Test barbarax4
Traceback (most recent call last):
  File "train.py", line 310, in <module>
    main()
  File "train.py", line 189, in main
    model.test()
  File "/opt_ext_one/Document/du/mmsr/codes/models/SRGAN_model.py", line 214, in test
    self.fake_H = self.netG(self.var_L)
  File "/home/hulk/miniconda3/envs/TF_and_Pytorch_GPU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hulk/miniconda3/envs/TF_and_Pytorch_GPU/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/hulk/miniconda3/envs/TF_and_Pytorch_GPU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt_ext_one/Document/du/mmsr/codes/models/archs/RRDBNet_arch.py", line 65, in forward
    fea = self.conv_first(x)
  File "/home/hulk/miniconda3/envs/TF_and_Pytorch_GPU/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hulk/miniconda3/envs/TF_and_Pytorch_GPU/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/hulk/miniconda3/envs/TF_and_Pytorch_GPU/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 1, 128, 128] to have 3 channels, but got 1 channels instead

Thank you

**Comment by Dejan1969** [comment]
Look like problem in validation set, check sizes of validation images, assuming you are using 4x validation image from LR set multiply by 4 must match size of  validation HR image, try to single out BW images if any
