### ISSUE TITLE
compiling dcn fails

### ISSUE THREAD

**Issue by dmmartindale** [open-mmlab/mmsr#73]
I am attempting to set up MMSR on a Windows 10 PC.  I've installed the most recent versions of CUDA from nVidia, Anaconda, and PyTorch.  I try compiling dcn from codes/models/archs/dcn from within the Anaconda Prompt cmd window and the first few lines of output are:

> python setup.py develop
> running develop
> running egg_info
> creating deform_conv.egg-info
> writing deform_conv.egg-info\PKG-INFO
> writing dependency_links to deform_conv.egg-info\dependency_links.txt
> writing top-level names to deform_conv.egg-info\top_level.txt
> writing manifest file 'deform_conv.egg-info\SOURCES.txt'
> reading manifest file 'deform_conv.egg-info\SOURCES.txt'
> writing manifest file 'deform_conv.egg-info\SOURCES.txt'
> running build_ext
> C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
>   warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
> 

Then the compile continues:

> building 'deform_conv_cuda' extension
> creating I:\AI-NN\MMSR\mmsr-master\codes\models\archs\dcn\build
> creating I:\AI-NN\MMSR\mmsr-master\codes\models\archs\dcn\build\temp.win-amd64-3.7
> creating I:\AI-NN\MMSR\mmsr-master\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release
> creating I:\AI-NN\MMSR\mmsr-master\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release\src
> Emitting ninja build file I:\AI-NN\MMSR\mmsr-master\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release\build.ninja...
> Compiling objects...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> [1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c I:\AI-NN\MMSR\mmsr-master\codes\models\archs\dcn\src\deform_conv_cuda.cpp /FoI:\AI-NN\MMSR\mmsr-master\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release\src/deform_conv_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
> FAILED: I:/AI-NN/MMSR/mmsr-master/codes/models/archs/dcn/build/temp.win-amd64-3.7/Release/src/deform_conv_cuda.obj
> cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c I:\AI-NN\MMSR\mmsr-master\codes\models\archs\dcn\src\deform_conv_cuda.cpp /FoI:\AI-NN\MMSR\mmsr-master\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release\src/deform_conv_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
> CreateProcess failed: The system cannot find the file specified.
> ninja: fatal: ReadFile: The handle is invalid.
> 
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
>     check=True)
>   File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 512, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 

---------------------------------------------

The first message suggests that it is looking for "cl", the command-line C++ compiler from Visual Studio.  So I installed Visual Studio Build Tools 2019, with only "C++ build tools" configured.  I try running setup.py; no change.  Next, I installed Visual Studio Community 2019, with only "Desktop development with C++" selected.  Try the build again, and it still fails in the same place.

Now, building dcn obviously requires a C++ compiler - but which one?  G++?  Visual Studio?  If VS, can it be the most recent version (2019) or must it be a specific version?  Cpp_extension.py seems to be looking for the VS compiler and not finding it - does it need some environment variables set up?  
The MMSR README.md says nothing about what compiler it expects to be available.

Could someone describe how they successfully compiled dcn under Windows 10?

**Comment by dmmartindale** [comment]
Additional info: VS 2019 requires you to run a batch file to set environment variables appropriately before you can do command-line compiles.  Running "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars32.bat" from within the Anaconda Prompt window (before the "python setup.py develop") fixes the initial "Error checking compiler version" warning.
But the dcn build still fails with many warnings and errors

**Comment by besit** [comment]
Hello, @dmmartindale 
Did you find the solution?
I think I have the same issue, at least when I run setup.py, it gives me similar errors in the start.
It finishes though and says 

```
Finished generating code
copying build\lib.win-amd64-3.7\deform_conv_cuda.cp37-win_amd64.pyd ->
Creating c:\users\besit\.conda\envs\mmsr\lib\site-packages\deform-conv.egg-link (link to .)
deform-conv 0.0.0 is already the active version in easy-install.pth

Installed z:\projects\neural\mmsr\codes\models\archs\dcn
Processing dependencies for deform-conv==0.0.0
Finished processing dependencies for deform-conv==0.0.0
```

But after this I can't execute test.py without error `Dataloader worker exited unexpectedly`

**Comment by besit** [comment]
Ok, I've installed the latest version of MSVC which is 14.25.28610 in VS 2019
But I still have a lot of errors appearing

1) `c1xx: fatal error C1356: unable to find mspdbcore.dll`
I tried adding paths containing mspdbcore.dll to the Path env variable, but it didn't help
something like: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64`
actually all 8 of them, which I have in bin directory, didn't help

2) ` fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.24 or newer.`
Seems like it's coded that I need version higher than 19.24, but the latest is 2019 14.25, maybe there is some kind of mess up in the VS versions or how they being read?

what command prompt gives me:
```
>python setup.py develop
running develop
running egg_info
writing deform_conv.egg-info\PKG-INFO
writing dependency_links to deform_conv.egg-info\dependency_links.txt
writing top-level names to deform_conv.egg-info\top_level.txt
reading manifest file 'deform_conv.egg-info\SOURCES.txt'
writing manifest file 'deform_conv.egg-info\SOURCES.txt'
running build_ext
building 'deform_conv_cuda' extension
Emitting ninja build file Z:\projects\Neural\mmsr2\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\TH -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\besit\.conda\envs\mmsr2\include -IC:\Users\besit\.conda\envs\mmsr2\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c Z:\projects\Neural\mmsr2\codes\models\archs\dcn\src\deform_conv_cuda.cpp /FoZ:\projects\Neural\mmsr2\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release\src/deform_conv_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: Z:/projects/Neural/mmsr2/codes/models/archs/dcn/build/temp.win-amd64-3.7/Release/src/deform_conv_cuda.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\TH -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\besit\.conda\envs\mmsr2\include -IC:\Users\besit\.conda\envs\mmsr2\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c Z:\projects\Neural\mmsr2\codes\models\archs\dcn\src\deform_conv_cuda.cpp /FoZ:\projects\Neural\mmsr2\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release\src/deform_conv_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
c1xx: fatal error C1356: unable to find mspdbcore.dll
[2/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /EHsc -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\TH -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\besit\.conda\envs\mmsr2\include -IC:\Users\besit\.conda\envs\mmsr2\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c Z:\projects\Neural\mmsr2\codes\models\archs\dcn\src\deform_conv_cuda_kernel.cu -o Z:\projects\Neural\mmsr2\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release\src/deform_conv_cuda_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61
FAILED: Z:/projects/Neural/mmsr2/codes/models/archs/dcn/build/temp.win-amd64-3.7/Release/src/deform_conv_cuda_kernel.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /EHsc -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\TH -IC:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\besit\.conda\envs\mmsr2\include -IC:\Users\besit\.conda\envs\mmsr2\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c Z:\projects\Neural\mmsr2\codes\models\archs\dcn\src\deform_conv_cuda_kernel.cu -o Z:\projects\Neural\mmsr2\codes\models\archs\dcn\build\temp.win-amd64-3.7\Release\src/deform_conv_cuda_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61
C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/include\yvals_core.h(439): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.24 or newer.
deform_conv_cuda_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    ], cmdclass={'build_ext': BuildExtension}, zip_safe=False)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\besit\.conda\envs\mmsr2\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\setuptools\command\develop.py", line 38, in run
    self.install_for_development()
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\setuptools\command\develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\besit\.conda\envs\mmsr2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\besit\.conda\envs\mmsr2\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\besit\.conda\envs\mmsr2\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

**Comment by dmmartindale** [comment]
No, I did not get it working under Windows.
I did note that the documentation for MMdetection (which is more extensive than what is available for MMSR) says that it has been tested under Ubuntu and Centos, but that Windows is not supported.
I've obtained another PC that I can install Ubuntu on, and will try again using that.

**Comment by dmmartindale** [comment]
Update:  The dcn code did not initially compile under Ubuntu either.  Issue #84 reports the errors I was seeing.  The problem turns out to be that Anaconda now installes Pytorch 1.5, and the dcn code hasn't been updated to be compatible with 1.5.  However, mmdetect *has* been updated, and it uses nearly-identical source code for the dcn operation.  My comment in issue 84 describes what I changed to update the dcn source.  With that change, dcn compiles (under Ubuntu).

However, even with this change, and using vcvars32.bat, dcn still fails to compile in Visual Studio.

**Comment by xinntao** [comment]
Not familiar with windows with dcn. 

BTW, 
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
