### ISSUE TITLE
Dataloader worker exited unexpectedly

### ISSUE THREAD

**Issue by besit** [open-mmlab/mmsr#74]
I try to enlarge a set of images using pretrained model RRDB_ESRGAN_x4.pth
Set is located in ./datasets/set5

What should I change in the file test_ESRGAN_woGT.yml ?
I try this:
```
name: RRDB_ESRGAN_x4
suffix: _test  # add suffix to saved images
model: sr
distortion: sr
scale: 4
crop_border: ~  # crop border when evaluation. If None(~), crop the scale pixels
gpu_ids: [0]

datasets:
  test_1:  # the 1st test dataset
    name: set5
    mode: LQ
    dataroot_LQ: ../datasets/Set5

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  upscale: 4

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/pretrained_models_v0.1/RRDB_ESRGAN_x4.pth
```
But it's giving me nothing but an error:
```
Testing [set5]...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\besit\.conda\envs\mmsr\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\besit\.conda\envs\mmsr\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\besit\.conda\envs\mmsr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Z:\projects\Neural\mmsr\codes\test.py", line 49, in <module>
    for data in test_loader:
  File "C:\Users\besit\.conda\envs\mmsr\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\besit\.conda\envs\mmsr\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Users\besit\.conda\envs\mmsr\lib\site-packages\torch\utils\data\dataloader.py", line 724, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "C:\Users\besit\.conda\envs\mmsr\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 49, in <module>
    for data in test_loader:
  File "C:\Users\besit\.conda\envs\mmsr\lib\site-packages\torch\utils\data\dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "C:\Users\besit\.conda\envs\mmsr\lib\site-packages\torch\utils\data\dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\besit\.conda\envs\mmsr\lib\site-packages\torch\utils\data\dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 60692) exited unexpectedly
```

**Comment by superaoe** [comment]
I'm getting the exact same error, I'm not sure what to do about it.

**Comment by banksio** [comment]
I was also encountering this issue. Found a resolution [here](https://stackoverflow.com/questions/24374288/where-to-put-freeze-support-in-a-python-script).

Quoting the answer:

> On Windows all of your multiprocessing-using code must be guarded by `if __name__ == "__main__":`

Eveything in `main.py` needs to be surrounded by a `def main():` and then at the bottom of the file, insert:
```
if __name__ == "__main__":
    main()
```
So it seems there's a bug in the code. Might only be an issue on Windows which could explain why it's not yet been fixed. I'll submit a pull request.

**Comment by superaoe** [comment]
Thank you for both the fix and the helpful information!

**Comment by besit** [comment]
@banksio
Thanks for the solution, Nathan. 
I am struggling now trying to compile DCN (Deformable Convolution). Did you manage to do this on Windows?

**Comment by singulart** [comment]
Faced the same issue, solution mentioned by @banksio confirmed to be working

**Comment by banksio** [comment]
> @banksio
> Thanks for the solution, Nathan.
> I am struggling now trying to compile DCN (Deformable Convolution). Did you manage to do this on Windows?

I can't say that I had an issue with that part, maybe submit a new issue?

**Comment by besit** [comment]
> > @banksio
> > Thanks for the solution, Nathan.
> > I am struggling now trying to compile DCN (Deformable Convolution). Did you manage to do this on Windows?
> 
> I can't say that I had an issue with that part, maybe submit a new issue?

No need to, I moved to ubuntu
